# docker-compose.yml

---
networks:
  traefik_default:
    external: true
  default:

services:

  app:
    image: ghcr.io/5mdt/url-fairy-bot:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      BASE_URL: ${BASE_URL:-localhost}
      IV_RHASH: ${IV_RHASH:-}
      BOT_TOKEN: ${BOT_TOKEN:-YOUR_BOT_TOKEN}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CACHE_DIR: ${CACHE_DIR:-/tmp/url-fairy-bot-cache/}
      COOKIES_DIR: ${COOKIES_DIR:-/config/}
      COOKIE_JAR_ENABLED: ${COOKIE_JAR_ENABLED:-false}
      FOLLOW_REDIRECT_TIMEOUT: ${FOLLOW_REDIRECT_TIMEOUT:-10}
      DOWNLOAD_ALLOWED_DOMAINS: ${DOWNLOAD_ALLOWED_DOMAINS:-}
      REWRITE_ALLOWED_DOMAINS: ${REWRITE_ALLOWED_DOMAINS:-}
      SPOTIFY_MIRROR_DOMAIN: ${SPOTIFY_MIRROR_DOMAIN:-fxspotify.com}
      INSTAGRAM_MIRROR_DOMAIN: ${INSTAGRAM_MIRROR_DOMAIN:-kkinstagram.com}
      REDDIT_MIRROR_DOMAIN: ${REDDIT_MIRROR_DOMAIN:-rxddit.com}
      THREADS_MIRROR_DOMAIN: ${THREADS_MIRROR_DOMAIN:-fx.akitsuki.me}
      TIKTOK_MIRROR_DOMAIN: ${TIKTOK_MIRROR_DOMAIN:-tfxktok.com}
      TWITTER_MIRROR_DOMAIN: ${TWITTER_MIRROR_DOMAIN:-fxtwitter.com}
      YOUTUBE_MIRROR_DOMAIN: ${YOUTUBE_MIRROR_DOMAIN:-yfxtube.com}
      YOUTUBE_SHORT_MIRROR_DOMAIN: ${YOUTUBE_SHORT_MIRROR_DOMAIN:-fxyoutu.be}
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    volumes:
      - cache:/tmp/url-fairy-bot-cache/
      - ${GLOBAL_DATA_FOLDER:-/Data}/url-fairy-bot/config:/config
    ports:
      - 8000:8000
    networks:
      - default
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          test -f
          "${CACHE_DIR:-/tmp/url-fairy-bot-cache/}/watch/sample.html"
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s

  nginx:
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.docker.network: traefik_default
      traefik.enable: true
      traefik.http.routers.url-fairy-bot.entrypoints: websecure
      traefik.http.routers.url-fairy-bot.rule: Host(`${BASE_URL:-localhost}`)
      traefik.http.routers.url-fairy-bot.service: url-fairy-bot
      traefik.http.routers.url-fairy-bot.tls: true
      traefik.http.routers.url-fairy-bot.tls.certresolver: ${LETSENCRYPT_RESOLVER_NAME:-letsencrypt-cloudflare-dns-challenge}
      traefik.http.services.url-fairy-bot.loadbalancer.server.port: 80
    ports:
      - ${PUBLIC_PORT:-80:80}
    logging:
      driver: none
    networks:
      - traefik_default
    volumes:
      - cache:/usr/share/nginx/html:ro

  cron:
    image: busybox:stable
    restart: unless-stopped
    environment:
      - FILE_TTL=${FILE_TTL:-3} #days
    volumes:
      - cache:/tmp/url-fairy-bot-cache/
    command: sh -c "find /tmp/url-fairy-bot-cache/ -type f -${FILE_TTL_TYPE:-mtime} +${FILE_TTL:-3} -delete > /dev/null; find /tmp/url-fairy-bot-cache// -type d -empty -delete > /dev/null; sleep 60m"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      driver: none

  # cobalt-api:
  #   image: ghcr.io/imputnet/cobalt:10
  #   restart: unless-stopped
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"
  #   networks:
  #     - default
  #   environment:
  #     API_URL: cobalt-api

volumes:
  cache:
