---
networks:
  traefik_default:
    external: true
services:
  bot:
    build: bot/
    environment:
      BOT_TOKEN: $BOT_TOKEN
      ALLOWED_USER_IDS: $ALLOWED_USER_IDS
      BASE_URL: $BASE_URL
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    volumes:
      - video_cache:/video_cache
  server:
    build: server/
    environment:
      BASE_URL: $BASE_URL
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.docker.network: traefik_default
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.rule: Host(`$BASE_URL`)
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.tls.certresolver: le
      traefik.http.services.jellyfin.loadbalancer.server.port: 80
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    networks:
      - traefik_default
    volumes:
      - video_cache:/video_cache:ro
  cron:
    build: cron/
    volumes:
      - video_cache:/video_cache
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
version: "3"
volumes:
  video_cache:

