---
networks:
  traefik_default:
    external: true
services:
  bot:
    build: bot/
    environment:
      BOT_TOKEN: $BOT_TOKEN
      BASE_URL: $BASE_URL
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    volumes:
      - video_cache:/video_cache
  nginx:
    image: nginx:stable-alpine-slim
    environment:
      BASE_URL: $BASE_URL
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.docker.network: traefik_default
      traefik.enable: true
      traefik.http.routers.url-fairy-bot.entrypoints: websecure
      traefik.http.routers.url-fairy-bot.rule: Host(`$BASE_URL`)
      traefik.http.routers.url-fairy-bot.service: url-fairy-bot
      traefik.http.routers.url-fairy-bot.tls: true
      traefik.http.routers.url-fairy-bot.tls.certresolver: le
      traefik.http.services.url-fairy-bot.loadbalancer.server.port: 80
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    networks:
      - traefik_default
    volumes:
      - video_cache:/video_cache:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d
  cron:
    image: busybox:stable
    volumes:
      - video_cache:/video_cache
    command: watch -n 60 'find /video_cache/ -type f -amin +1440 -delete' > /dev/null
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
version: "3"
volumes:
  video_cache:
