# lint-python-ruff.yml

---

name: "Lint: python/ruff"

on:
  - push
  - pull_request

jobs:
  lint-python-ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./bot"
