---

name: "Lint: python/black"

on:
  - push
  - pull_request

jobs:
  lint-python-ruff:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./bot"
