# lint-docker-hadolint.yml

---

name: "Lint: docker/hadolint"

on:
  - push
  - pull_request

jobs:
  lint-docker-hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./bot/Dockerfile"
