# lint-python-black.yml

---

name: "Lint: python/black"

on:
  - push
  - pull_request

jobs:
  lint-python-black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: "./bot"
          options: "--check --verbose"
